-- Minimal disposable PostgreSQL 17 schema for atomic_bulk_variant_import.sql.
-- This file is test infrastructure only and must never be applied to production.

create role anon nologin;
create role authenticated nologin;
create role service_role nologin;

create schema auth;

create table auth.users (
  id uuid primary key,
  created_at timestamptz not null default pg_catalog.now()
);

insert into auth.users (id)
values ('00000000-0000-4000-8000-000000000001');

create table public.products (
  id bigint generated by default as identity primary key,
  name text,
  category text,
  slug text unique,
  price text,
  base_price numeric,
  description text,
  image_url text,
  full_image_url text,
  status text,
  sort_order integer default 0,
  updated_at timestamptz default pg_catalog.now()
);

create table public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  active boolean not null default true
);

create table public.product_variants (
  id bigserial primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  name text not null,
  color_code text,
  color_name text,
  sku text,
  image_url text,
  full_image_url text,
  price numeric,
  status text default 'available',
  sort_order integer default 0,
  stock integer check (stock is null or stock >= 0),
  created_at timestamptz default pg_catalog.now(),
  updated_at timestamptz default pg_catalog.now()
);

create or replace function public.set_products_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = pg_catalog.now();
  return new;
end;
$$;

create trigger set_product_variants_updated_at
before update on public.product_variants
for each row
execute function public.set_products_updated_at();

create or replace function public.fill_variant_full_image_url()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.full_image_url is null or pg_catalog.btrim(new.full_image_url) = '' then
    new.full_image_url = new.image_url;
  end if;
  return new;
end;
$$;

create trigger fill_variant_full_image_url
before insert or update of image_url, full_image_url on public.product_variants
for each row
execute function public.fill_variant_full_image_url();

alter table public.products enable row level security;
alter table public.admin_users enable row level security;
alter table public.product_variants enable row level security;
