// Generated by scripts/generate-blog-registry.ts. Do not edit manually.
import type { BlogPostMeta } from "@/types/post";
import type { MdxPostLoader } from "./registry-types";

export const mdxPostMetadata: BlogPostMeta[] = [
  {
    "slug": "qua-tot-nghiep-handmade-y-nghia",
    "title": "Quà Tốt Nghiệp Handmade Làm Riêng Cho Người Nhận | LenTiny",
    "description": "Chọn quà tốt nghiệp handmade làm riêng theo sở thích người nhận. Tiny gợi ý mẫu theo khoảng giá mong muốn và gửi ảnh thành phẩm trước khi giao.",
    "ogTitle": "Quà Tốt Nghiệp Handmade Làm Riêng, Duyệt Mẫu Trước Khi Giao",
    "ogDescription": "Kể Tiny nghe dịp trao quà, khoảng giá mong muốn và sở thích người nhận. Tiny sẽ gợi ý mẫu, báo giá và xác nhận lịch trước khi làm.",
    "category": "Quà tốt nghiệp handmade",
    "categorySlug": "qua-tang-bang-len",
    "tags": [
      "qua-handmade",
      "huong-dan"
    ],
    "searchText": "quà tốt nghiệp quà tốt nghiệp handmade quà tốt nghiệp cho bạn nữ quà tốt nghiệp cho bạn nam hoa len tốt nghiệp thú len đội mũ cử nhân quà ra trường",
    "publishedAt": "2026-07-17",
    "updatedAt": "2026-07-18",
    "author": "Tiny",
    "eyebrow": "Quà tốt nghiệp - Đặt làm riêng",
    "breadcrumbLabel": "Quà tốt nghiệp handmade",
    "h1": "Quà tốt nghiệp handmade dành riêng cho người bạn muốn chúc mừng",
    "lead": "Cho Tiny biết dịp trao quà, nơi cần giao, khoảng giá bạn mong muốn cùng màu sắc hoặc sở thích của người nhận. Tiny sẽ gợi ý một món quà vừa ý và báo giá rõ ràng trước khi bắt đầu làm.",
    "excerpt": "Chọn hoa len, thú len hoặc set quà làm riêng; Tiny gợi ý mẫu theo sở thích người nhận và khoảng giá bạn mong muốn.",
    "image": "https://res.cloudinary.com/djn2kd2hh/image/upload/v1784302075/lentiny/blog/qua-tot-nghiep-handmade-y-nghia/qua-tot-nghiep-handmade-lam-rieng.jpg",
    "imageAlt": "Gấu len đội mũ cử nhân, bó hoa len và giấy chứng nhận làm quà tốt nghiệp handmade",
    "ogImage": "https://res.cloudinary.com/djn2kd2hh/image/upload/v1784302075/lentiny/blog/qua-tot-nghiep-handmade-y-nghia/qua-tot-nghiep-handmade-lam-rieng.jpg",
    "status": "published",
    "featured": true,
    "ctaType": "gift",
    "heroCta": {
      "primaryLabel": "Kể Tiny nghe về món quà",
      "secondaryLabel": "Xem cách đặt theo yêu cầu",
      "secondaryHref": "/san-pham/thu-len-theo-yeu-cau"
    }
  }
];
export const mdxPostLoaders: Record<string, MdxPostLoader> = {
  "qua-tot-nghiep-handmade-y-nghia": () => import("@/content/blog/qua-tot-nghiep-handmade-y-nghia.mdx")
};
