import { readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import matter from "gray-matter";
import { validateMdxPostMeta } from "../lib/blog/schema";

const projectRoot = process.cwd();
const contentDir = path.join(projectRoot, "content", "blog");
const outputFile = path.join(projectRoot, "lib", "blog", "post-registry.generated.ts");

async function getMdxFiles() {
  try {
    return (await readdir(contentDir))
      .filter((file) => file.endsWith(".mdx"))
      .sort();
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return [];
    throw error;
  }
}

async function main() {
  const files = await getMdxFiles();
  const metadata = [];
  const loaders: string[] = [];

  for (const file of files) {
    const slug = file.slice(0, -4);
    const source = await readFile(path.join(contentDir, file), "utf8");
    const parsed = matter(source);
    metadata.push(validateMdxPostMeta(parsed.data, slug));
    loaders.push(
      `  ${JSON.stringify(slug)}: () => import("@/content/blog/${file}")`
    );
  }

  const source = `// Generated by scripts/generate-blog-registry.ts. Do not edit manually.
import type { BlogPostMeta } from "@/types/post";
import type { MdxPostLoader } from "./registry-types";

export const mdxPostMetadata: BlogPostMeta[] = ${JSON.stringify(metadata, null, 2)};
export const mdxPostLoaders: Record<string, MdxPostLoader> = {
${loaders.join(",\n")}
};
`;

  await writeFile(outputFile, source, "utf8");
  console.log(`Generated blog registry with ${files.length} MDX post(s).`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
